# GET https://192.168.188.29:5443/brightness 
GET http://localhost:5000/brightness

###


###

POST http://localhost:5000/brightness
content-type: application/json

{
    "target": 50,
    "duration": 1
}

###

GET http://localhost:5000/temp 

###

POST http://localhost:5000/temp
content-type: application/json

{
    "target": 0,
    "duration": 3
}