DELETE https://10.0.1.101:5443/brightness 

###

DELETE http://localhost:5000/temp

###


###
DELETE http://localhost:5000/temp

###

###
GET http://localhost:5000/brightness

###


POST http://localhost:5000/brightness
content-type: application/json

{
    "target": 100,
    "duration": 1
}

###

POST http://0.0.0.0:5000/temp
content-type: application/json

{
    "target": 100,
    "duration": 5
}